version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: 21
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    assignees:
      - pva2007
    versioning-strategy: increase
    cooldown:
      default: 7

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: 21
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    assignees:
      - pva2007
